### ISSUE TITLE
Allow group rank as a replacement for nickname format

### ISSUE THREAD

**Issue by evaera** [evaera/RoVer#100]
Implementation steps:

- Add a new server setting called `nicknameGroup`, default null
- Add a new command called !nicknamegroup <groupid>, use NicknameFormatCommand.js as a starting point
- Add a new replacement called %RANK% in Util.formatDataString.
  - Process and add the rank key to `data` in DiscordMember.getNickname. 
  - Use return value of `await DiscordServer.getRobloxMemberGroups(data.robloxId)` to get the users' groups. 
    - This returns an array of objects each representing a group.
    - Loop through to find a group that matches the server's nicknameGroup. 
    - Use the `Role` key from the group object.
  - If the user is not in the nicknameGroup, return "Guest". 
  - If the server has no nicknameGroup, then send an empty string.

**Comment by ZachCurtis** [comment]
I personally would like to have the option to bind a label string to a specific rank, rather than display the ranks full name. This would also be helpful with the !NicknameFormat command.

**Comment by evaera** [comment]
Added in #112

**Comment by suufi** [comment]
Happy :100:
