### ISSUE TITLE
```markdown does not work

### ISSUE THREAD

**Issue by StellarDoor5319** [evaera/RoVer#108]
The bot is sending messages using the following syntax:

    ```markdown
    # Group ID XXX
    Roles X, X-X
    ```

however, Discord does not support the "`markdown`" (as there is no syntax highlighting). It should just be:

    ```
    # Group ID XXX
    Roles X, X-X
    ```

**Comment by evaera** [comment]
![image](https://user-images.githubusercontent.com/2489210/36931958-63aa46b4-1e8f-11e8-9f99-d72692fd7916.png)

**Comment by StellarDoor5319** [comment]
@evaera Why does it even use syntax highlighting, when we could have

    **Group ID XXX**
    Roles X, X-X

which also works in the mobile apps.

**Comment by evaera** [comment]
I think it makes it easier to read when they are in code blocks and use colors, but there's no real reason other than that. Just the way it happened to be done. Lots of other ways are equally valid, this is just the one I chose
