### ISSUE TITLE
how can i stop bot send command into other channels

### ISSUE THREAD

**Issue by DragonHero221** [evaera/RoVer#109]
i just new to be a leader of discord group of roblox and i don't know how to disable a bot for stop send a command when people `!verify`,`!update` etc i just want bot to read only 1 channels

**Comment by DragonHero221** [comment]
i did permission on RoVer but still it not working they keep send a message to other channels

**Comment by suufi** [comment]
Change the permissions on all other channels to deny RoVer to read or send
messages. However, on the one channel you want to use as a verification
channel, allow read and send permissions.

**Comment by DragonHero221** [comment]
i did but it still send on other channels

**Comment by suufi** [comment]
That's most likely because of you giving the bot the Administrator
permission or the bot having a role above itself that can post to any
channel.

**Comment by DragonHero221** [comment]
the bot on my server have 2 role `Rover` and `Bot` all each role i set all permission to deny to read/send message but yea it still send on channels that i did, and i didn't give any Administrator to bot and yet i also turn off Administrator of RoVer role and yet it still able to send message commands

**Comment by suufi** [comment]
Join the RoVer Discord server and I'll see what your problem is.

**Comment by DragonHero221** [comment]
where is the code to RoVer Discord server?

**Comment by suufi** [comment]
In the README.md

**Comment by DragonHero221** [comment]
i didn't find it..

**Comment by suufi** [comment]
It says "chat: xxx online"
