### ISSUE TITLE
Show a helpful message after a couple failed verifications

### ISSUE THREAD

**Issue by evaera** [evaera/RoVer#116]
When a verification doesn't work, people like to keep spamming it anyway because they are frustrated, as seen here:

![Image](https://i.imgur.com/LdNxlGU.png)

After a couple (manually triggered) failed verifications, it may be prudent to show a different message helping users who are having trouble.

Also, it may be helpful to tell the user how to re-verify by showing the link again if they run !verify while verified and no changes were made. Don't want that link to show up if it actually is verifying them for the first time / correcting group ranks, though.

Failed message template:

----------------------------

:interrobang: Looks like you are having trouble verifying your account! Here are some things you can try:

- Try visiting https://verify.eryn.io/ in an incognito / private browser window. (It's possible you are signed into the wrong Discord account in your browser)
- If you are using the profile code verification method, make sure that the code isn't getting filtered after you save it. If it is, try using the in-game method or generating a new code.
- Make sure you typed in the right Roblox username when trying to verify.

**Comment by suufi** [comment]
how about we add stop being stupid and actually follow the instructions?
:eyes:
