### ISSUE TITLE
Not enough power

### ISSUE THREAD

**Issue by explosin59** [evaera/RoVer#12]
Bot keeps saying it doesn't have enough modify power when it is the top role in server and has admin power (Issue is when other people try to do it without even any roles.)

**Comment by devSparkle** [comment]
The bot, due to Discord limitations, cannot modify any user which is either Server Owner or has Administrator permissions in the server.

**Comment by MetalRuller** [comment]
Having this issue too.
Bot cannot edit user's roles even with Administrator perms (and other members not having any perms)

**Comment by evaera** [comment]
@explosin59 @MetalRuller I can't get this to reproduce on my end. Please invite me to the servers where you are having the issues and I will take a look.

**Comment by MetalRuller** [comment]
@evaera https://discord.gg/TjCUDNG
I'm also on Café Dev if you need to ping me.
<@234358652683812865>

**Comment by evaera** [comment]
The bot has been adjusted to use sharding so it should scale a lot better. Let me know if any further issues arise. I'm going to be upgrading the server soon because I'm quickly running out of memory.
