### ISSUE TITLE
Add a generalized configuration command

### ISSUE THREAD

**Issue by evaera** [evaera/RoVer#120]
Running a command with no arguments (status quo) doesn't feel intuitive. Running with no arguments should display the current value.

Unsure how the user should indicate they want to change a setting to default. May be difficult to do this with the built-in Commando argument parsing system.

**Comment by antonio6643** [comment]
We could add tags such as: $all, $default, $administrators to target certain groups/things, making it easier to complete some tasks.

**Comment by evaera** [comment]
discord.js-commando added union types which will make this easier
