### ISSUE TITLE
Limit number of new lines in a user blurb from WhoIs

### ISSUE THREAD

**Issue by H4PPYZ** [evaera/RoVer#138]
Hey, I mod a large Roblox Discord server and usually I'd see people doing the '?whois @username/username' command to see their Roblox account connected. People who have large indented blurbs make the text channel flood. An example to this is shown here:

![image](https://user-images.githubusercontent.com/9408910/40884798-94e32c22-671a-11e8-9c88-f11ad872f166.png)

As you can see, the bot floods the text channel with a wall of text depending on the usernames blurb, this is getting quite annoying so I hope you minimize or cap it.

**Comment by evaera** [comment]
We can solve this by making a minimum of new line characters per blurb. Also, perhaps a setting to allow server owners to disable the blurb display.
