### ISSUE TITLE
Send NUDES?! WTF?

### ISSUE THREAD

**Issue by jjhowe02** [evaera/RoVer#140]
Did you code this to Rover?! [https://gyazo.com/f2cfae2b25293cb0ecc7df1de865ffbe](url)

I HOPE YOU REALIZE THIS ISN'T A ROBOT MADE FOR SEX RIGHT?

**Comment by evaera** [comment]
RoVer's welcome text can be customized by any Discord user that can manage a server RoVer is in, and it has nothing to do with us.
