### ISSUE TITLE
Even if a role is named anything like "[!] RoVer Updater", RoVer should still count it as the updater role

### ISSUE THREAD

**Issue by xFroosh** [evaera/RoVer#141]
So, I'm the Vice Chairman of a group and I was binding some roles to ranks for people to have depending on what job they have. And I wanted to give people the **Updater** permission, which I did. But the apparent problem was that I named it "[!] RoVer Updater" instead of the default "RoVer Updater" name. Which didn't give people the permission to use the update command unless I full on give the role the "Manage Roles" permission, which is required for people to use the updater command. 
<img width="480" alt="manageroles" src="https://user-images.githubusercontent.com/24479226/41120632-1615caf6-6a64-11e8-819d-7cffccfa7dd6.png">

But what I'm trying to figure out is, why can't RoVer classify it as the updater role regardless of what else the role has set as it's name? I don't want to give the role the "Manage Roles" permission to avoid anyone deleting any roles or adding roles without my approval. 

So, is it possible that for things like "RoVer Bypass" or "RoVer Admin" and etc. for any other future features like these coming to RoVer could just classify the role as "RoVer [name]" regardless of what else is included in the name like "[!] RoVer Updater" 

Or at least have some command to choose what role gives what ever RoVer permission they choose?

**Comment by evaera** [comment]
Is there a specific reason you want to have `[!] ` in your role name? The reason that the roles use an exact match right now is to keep the permissions simple. I want to add a more robust way of adding permissions to specific roles at some point in the future, but for now it's probably just going to stay as an exact match to make it easier to deal with.

**Comment by xFroosh** [comment]
So in the server, we have the normal group ranks and then there are some roles that'll give them permissions like these
<img width="206" alt="rankings" src="https://user-images.githubusercontent.com/24479226/41123293-24f01902-6a6c-11e8-8416-b82be1f697ca.png">
And to make the role stand out and be a little bit more noticeable to those who maybe want to find out who has what permissions (this probably isn't making sense)

So what I did was add [!] to roles like the ones shown in the image. It's easier for me and others to figure out which role is which and what role has permissions and what role doesn't. And it's easier to give a role permissions and give it to people who have a certain rank, than to give the same permissions I think they should have to multiple different roles because it'd become a tedious task to do and sometimes I'd probably end up confusing myself and starting over

**Comment by evaera** [comment]
I agree that it's tedious managing an extra role on everyone, but I'm not sure I want to add the extra layer of complexity to the code base right now. It will definitely come at some point in the future, after I have a chance to refactor RoVer as a whole.

**Comment by xFroosh** [comment]
Well alright, but if thats the case then does the role have to be named specifically as "RoVer Updater" or can it be named "RoVer Updater [!]" if I was to change the name?

**Comment by evaera** [comment]
@xFroosh It needs to be named "RoVer Updater" exactly for now. Will probably allow any role in the future.
