### ISSUE TITLE
!unbind and !unbindall doesnt seem to work

### ISSUE THREAD

**Issue by Tuck642** [evaera/RoVer#145]
Hello I am trying to unbind a role from being verified automatically so I ran the command !unbind <Role> and it said it has been unbinded then I do !bindings and that role is still there and when I test it out and do !verify it still gives me that role.

The staff on the discord don't help.

![rd](https://user-images.githubusercontent.com/39452571/43476097-b557cebc-94c5-11e8-94d4-cf832eecdb10.PNG)

**Comment by evaera** [comment]
Hello,

I can't reproduce this issue. I've successfully bound and unbound roles in my own servers. Could you please invite me to your server so I can investigate further? Thanks

**Comment by Tuck642** [comment]
I made a new discord for it, you'll have administrator perms when you join. I don't know if I'm doing something wrong or what. The problem still occurs.
The link is https://discord.gg/Q74WdUv

**Comment by evaera** [comment]
@Tuck642 Hey there, sorry about any confusion. The `!unbind` and `!unbindall` commands only affect group bindings (which are created with the `!bind` command). 

The Verified Role and UnverifiedRole commands are considered special cases and therefore have a different pattern when you want to remove them: Just run the command by itself with no argument, e.g.: `!VerifiedRole`. 

I'm aware that this is a confusing design so I apologize for any inconvenience this may have caused you. There are plans to simplify this process but it will take a while to get everything in place for that. Let me know if you have any further issues.
