### ISSUE TITLE
Bot doesn't change nickname or add role

### ISSUE THREAD

**Issue by ElliottMVP** [evaera/RoVer#15]
I have confirmed that I correctly set it up, the bot has Administrator permissions and the highest role in the server. Please help.

**Comment by theseanconn** [comment]
I have this same issue

**Comment by ElliottMVP** [comment]
From my tests, it appears that it does change their nickname and adds the role from one of my servers, not 100% sure from the others.
(Tests conducted with !RoVerUpdate)

**Comment by evaera** [comment]
@ElliottMVP @theseanconn Please verify the issue is still happening. I've identified an issue in the hosted version server that may have been causing the majority of these issues.

**Comment by theseanconn** [comment]
I believe this issue is still happening.
