### ISSUE TITLE
Unlinking of Accounts to Deleted Discord Accounts/Re-Verifying with a separate Discord account.

### ISSUE THREAD

**Issue by DeverusLazvari** [evaera/RoVer#151]
Morning,

I think the title explains the gist of it. However, how would one go about Verifying their already linked ROBLOX Account with a separate discord account?

The previous discord account is now unavailable due to complications and henceforth inaccessible.

Thanks.

**Comment by evaera** [comment]
Just go to https://verify.eryn.io/ and re-verify.
