### ISSUE TITLE
Add a command that toggles auto verification

### ISSUE THREAD

**Issue by HolyItsTio** [evaera/RoVer#152]
Since I'm trying to use another account on a specific server to get group space, auto verification doesn't let me have roles, as soon as I chat they get removed which is really stressing.

**Comment by whasonyt** [comment]
This is a suggestion, not a issue. Please join the Rover server to submit suggestions.

**Comment by evaera** [comment]
@HolyItsTio Please use a [RoVer Bypass](https://rover.link/#magic-roles) role for this use case.
