### ISSUE TITLE
Are you falsifying your guild count? 

### ISSUE THREAD

**Issue by wr1ght** [evaera/RoVer#155]
**Gee golly, you sure do love misinforming users.**
Let's take a look at your guild count... which seems to only be available on the bot's Discord status.
![image](https://user-images.githubusercontent.com/30602871/46309731-3380b880-c58b-11e8-9b7e-28510a569b2f.png)

Wow! 27K+ guilds. Nice!
(assuming you haven't locally modified your code to differ from the actual guild count)

But wait... why does your README have a static text of "45K+?
![image](https://user-images.githubusercontent.com/30602871/46309754-54490e00-c58b-11e8-83c5-4da4e61e1387.png)
https://github.com/evaera/RoVer/blob/master/README.md

Hold on... am I seeing things? Let's take a look at https://eryn.io/
![image](https://user-images.githubusercontent.com/30602871/46309835-96724f80-c58b-11e8-8b4d-575d1b68bbb3.png)

Wow, a whopping **65K+** Discord guilds! My gosh, you sure have dropped thousands of guilds.

The point is, I'm seeing over three different counts here and I highly doubt any of them are even real.

**Comment by evaera** [comment]
- The number on the bot is the number of active guilds
- The number on eryn.io is the total number of guilds
- The number on the readme is the same as the above, but not as up to date
