### ISSUE TITLE
Client.json didn't had the options told in readme. 

### ISSUE THREAD

**Issue by chrissie1234** [evaera/RoVer#160]
Hello,

The client.json is not having the feature that is told in Readme. Only the token. 
Please fix it. 

Best regards, 
Chris

**Comment by PhoenixShay** [comment]
Can you give some more information? Perhaps post the config.json with **sensitive information removed**, as well as any console output?

**Comment by evaera** [comment]
The client.json options must be added to the config manually, as they are all optional.
