### ISSUE TITLE
Nickname format issue 

### ISSUE THREAD

**Issue by xFroosh** [evaera/RoVer#163]
Every time I change the nickname format, it doesn't update everyone's usernames to the format it was set to. 

RoVer has the administrator permission and it's above all roles in the server, so I'm not sure what the problem is. Anyone who joined the server after RoVer was put in the server their names don't even get updated to their ROBLOX username. Anyone before has their nickname set to their ROBLOX name.

**Comment by evaera** [comment]
RoVer does not have the ability to update everyone in the server at once due to it being an expensive operation. However, it will automatically update people if they are active (chatting) at least every two hours.

**Comment by xFroosh** [comment]
Everyone was manually updated to make sure everyone had the correct format and it's still not updating to the nickname format provided.

**Comment by evaera** [comment]
Is this still happening? Can you send me your server ID?

**Comment by xFroosh** [comment]
We gave it a few days and yes it's still happening. 

Here's the ID - 476800588965740557

**Comment by evaera** [comment]
@xFroosh Hi, it appears that your nickname format has *not* been changed -- it's still the default `%USERNAME%`. Can you send me the full command that you were trying to use to change the format?

**Comment by evaera** [comment]
Closed as no response from bug report author and everything seems to be working correctly from my end.
