### ISSUE TITLE
Getroles/Verify isn't working.

### ISSUE THREAD

**Issue by AdministratorSpider** [evaera/RoVer#168]
Verify and Getroles aren't working, I binded all the roles and a member of mine said !verify and they didn't get their roles then he tried !getroles and still didn't get his roles.

**Comment by evaera** [comment]
And is your RoVer role higher than the roles you've bound in the role list as mentioned in the [readme](https://rover.link/#readme)?

**Comment by AdministratorSpider** [comment]
No and I just fixed it, apparently it wasn't over the role.
