### ISSUE TITLE
Group rank to Discord role link does not work if ROBLOX rank ID is 100

### ISSUE THREAD

**Issue by Ali365Dash** [evaera/RoVer#17]
Caused by an issue with an Discord emoji existing with the use :100:. 
![image](https://cloud.githubusercontent.com/assets/7354090/25566617/73dc3ce2-2dd4-11e7-90e7-a999ed7ced58.png)
![image](https://cloud.githubusercontent.com/assets/7354090/25566620/815616e0-2dd4-11e7-83bd-43642ecb77d6.png)

Recommended solution: change character that seperates arguments, but any solution that works is fine.
~~Could also be solved by recognising the emoji as the text `:100:`.~~

**Comment by OnlyTwentyCharacters** [comment]
Emojis can't recognised by the emoji string you type like `:100:` in code. They're read as unicode.

If you do 1156950: 100 :Staff, that'll work.

**Comment by Ali365Dash** [comment]
I'll keep this open since I think there should be a more permanent solution than a workaround, but thanks for the response.

**Comment by evaera** [comment]
I feel like the commands in RoVer were hastily implemented. I want to redo them using Discord.js's built in Commando library. This issue will be fixed along with #4 soon.

**Comment by evaera** [comment]
New command format for this now
