### ISSUE TITLE
Un-Verify

### ISSUE THREAD

**Issue by KillerQueenBitesZaDusto** [evaera/RoVer#171]
I made this account for this one post, I want to Un-verify, I don't want to be Verified anymore. My Discord is 『Kira Yoshikage』#2545 and I want it Un-Verified.

**Comment by KillerQueenBitesZaDusto** [comment]
It said you opened it 3 hours ago, can you Un-Verify me?

**Comment by whasonyt** [comment]
Why do you want to be unverified so much?

**Comment by evaera** [comment]
Issues are for problems with the functionality of the open source RoVer bot code.
