### ISSUE TITLE
Rover

### ISSUE THREAD

**Issue by korndolly** [evaera/RoVer#172]
I uninstalled Rover as it wasn't working. I reinstalled it and the issue is worse. No one is being verified. Before people were automatically verified if they were already verified on Rover, and the verify command isn't working. I tried to unbind all roles to reconfigure it but they are still bound and I am unabke to use any function on it. I could really use some help on this.

**Comment by evaera** [comment]
This report is unactionable. Please follow the directions found at https://rover.link/#readme. Automatic verification is an intended feature; users only verify once for all servers.

**Comment by korndolly** [comment]
That was the issue I laid out, no one is being verified. I'm following the read me section but the bot is just not responding at all
