### ISSUE TITLE
Rover doesn't know what to do if someone disconnects his account 

### ISSUE THREAD

**Issue by TheFutureKnight** [evaera/RoVer#174]
If someone had connected their Roblox and Discord account using Rover, entered my server and got their roles, then disconnects his account again, the roles will remain, this issue will lead into people that leave the roblox group can remain in some roles even tho they left, and that's because they disconnected their account.
Contact me as soon as this is fixed. Thanks.

**Comment by PhoenixShay** [comment]
Disassociating your account with your Discord is no longer possible.
