### ISSUE TITLE
Offer a setting to not remove certain roles that are linked to group rank.

### ISSUE THREAD

**Issue by EtiTheSpirit** [evaera/RoVer#175]
There's some people in my Discord server that are not in the group on Roblox. In my group, I have a role designated "Classic Player" for those who played the original version of my game. This role is linked into RoVer, of course.

I've run into a repeat issue where people who I personally know as classic players are having the Discord role removed from them by RoVer because they aren't in my group.

I'd like a way to specify certain roles that can't be automatically removed by RoVer. This would mean that RoVer can *give* the role to someone, but it can't take it from someone, which causes manual roles to persist. This would be counter-intuitive to the idea of keeping RoVer in sync with a group, but it's become a hassle to keep re-adding the role to people.

**Comment by evaera** [comment]
You can use/bind a `RoVer Bypass` role to make RoVer ignore a user completely, but it would be nice to have this customizable on a per-role basis.

**Comment by Rythian2277** [comment]
A bit of a necrobump for an old issue but could this be resolved via virtualgroup, call it "Role" with an argument of a role name/id. The VG would just need to check if the player has a role with the corresponding name/id and return true if the member has that role.
