### ISSUE TITLE
Removing status from Bot on Self-Host

### ISSUE THREAD

**Issue by Platinuuum** [evaera/RoVer#177]
In basics, what I'm saying is that when someone decides to self-host the bot on his/her device, or on a remote device, they should be able to enable or disable the status. Status being the "listening to **X users**", "listening to **!rover**", "watching **2 servers"**, etc.
![image](https://user-images.githubusercontent.com/46118142/50410801-50630b80-07c9-11e9-9db1-beb1fbffbed3.png)

**Comment by evaera** [comment]
RoVer is open source, so please feel free to implement any custom features you need.
