### ISSUE TITLE
RoVer stopped responding commands on my discord server

### ISSUE THREAD

**Issue by Alfhy** [evaera/RoVer#183]
Guild ID: 402215846707068930
For more than 1 month, RoVer has stopped responding to any command, and it has administrator permission.
I do not know why but one day he just stopped responding.
Please fix this.

**Comment by evaera** [comment]
You changed your command prefix to `a;`, thus RoVer is not responding to your commands when you use `!`. To change your prefix, use `@Rover prefix !` to restore it back to !.
