### ISSUE TITLE
Help on how to unverify my Roblox to Discord

### ISSUE THREAD

**Issue by Famalamadingdong** [evaera/RoVer#184]
How do I unlink the roVer account to my Roblox account on Discord. I keep joining servers and don't want my Roblox account to be linked anymore to my Discord servers. 
I have looked into it and it keeps showing me on how to verify but I don't want it my Discord to be linked with my Roblox account. 
It would be much appreciated if you could help me
Thanks

**Comment by evaera** [comment]
You can make an alt account and then verify on that to override your verified account. For further inquiries please join our support server found on rover.link

**Comment by Famalamadingdong** [comment]
Thanks, I’ll try it

On 13 Feb 2019, at 23:16, eryn L. K. <notifications@github.com<mailto:notifications@github.com>> wrote:


You can make an alt account and then verify on that to override your verified account. For further inquiries please join our support server found on rover.link<http://rover.link>

**Comment by Famalamadingdong** [comment]
I have made my alt account and verified it. But my real Discord account still has my roblox username attached to it even though I deauthorised it completely. 
I also joined your support server for additional help
Thanks
