### ISSUE TITLE
Rover Bypass role issues

### ISSUE THREAD

**Issue by Zeenyoo** [evaera/RoVer#188]
I have RoVer on my Matchmaking server for CounterBlox, and i use Rover Bypass as the Verified Role so whenever they verify, it renames them to "[0] PlayerName" and it wouldn't update to that everytime the player typed, only once, but my issue with that, whenever someone does !verify, it updates their name but it doesn't give them the Rover Bypass Role, it keeps them with the Not Verified role. Can someone help me?
![18f8354fb0d3f18a8675d2addbc543ca](https://user-images.githubusercontent.com/26187990/53512154-cb35f480-3aa0-11e9-81ee-3a69969c28dc.png)

**Comment by evaera** [comment]
Please join the [support server](https://discord.gg/7yfwrat) for usage help
