### ISSUE TITLE
Error when using !setmessage

### ISSUE THREAD

**Issue by ElliottMVP** [evaera/RoVer#19]
![img_0025](https://cloud.githubusercontent.com/assets/27061626/25588203/4189f25e-2e9f-11e7-8c63-2c9d333c2c6b.PNG)

**Comment by ElliottMVP** [comment]
@evaera I assume this is a serious issue.

**Comment by evaera** [comment]
@ElliottMVP Thanks for reporting this, I've applied a patch to fix it
