### ISSUE TITLE
Wrong Account Authorized

### ISSUE THREAD

**Issue by FelineRin** [evaera/RoVer#191]
One of my friends can’t be verified because the verification keeps authorizing her old account instead of her new one. She has her new account out, but it keeps saying Hello to her old account whenever she presses authorize.

**Comment by gitrous** [comment]
There is a command !reverify

**Comment by evaera** [comment]
Please sign in to the correct account you want to verify in your browser.

**Comment by FelineRin** [comment]
Yes, it was on the correct account. She has it on and everything, but
everytime it authorizes, it goes back to her old account that she doesn’t
even remember the password to. We will try again, but if it continues not
to work, I will try to contact again. :/

**Comment by evaera** [comment]
If it's indicating she's on her old account, then she's on her old account. Just sign in to the new account.

**Comment by evaera** [comment]
Please join the Discord support server. Issues are for bugs or features that pertain to the bot itself.
