### ISSUE TITLE
Most unicode quotation marks are ignored

### ISSUE THREAD

**Issue by travddm** [evaera/RoVer#193]
As the title states, all Unicode characters marked `Quotation Mark=Yes` except for U+0022 and U+0027 (regular quotation and apostrophe, respectively) are ignored by the bot when entering commands. This is particularly annoying when copy/pasting roles from a word processor (google docs, microsoft word) which has smart quote support.

Ex: Using U+201C and U+201D (directional quotation marks) in a command:
`!bind “Member” 0123456:1`

Result:
`You provided an invalid role. Please try again.`

This may be uncommon usage, so I completely understand if you decide not to implement this. Just thought I'd at least bring it to attention

**Comment by evaera** [comment]
The code for this exists in the command library that we use and not RoVer itself, so we won't be able to fix this on our end.
