### ISSUE TITLE
Developer Forums Suspension Detection

### ISSUE THREAD

**Issue by Rythian2277** [evaera/RoVer#199]
At this moment in time, if a user is suspended on the developer forums, the system still classes them as a member and grants them any bound roles. Would it be possible to add a check for suspensions and if that check is true, the role is not given with some sort of message indicating why to the user?

(Suspended users on the forums have a clear indication on the site for suspended members such as seen here:)
![image](https://user-images.githubusercontent.com/26336033/59805133-52c1a080-92e8-11e9-8774-3f4dfa39872a.png)

**Comment by evaera** [comment]
Not sure if this makes sense, suspended users are still members. It would probably depend on how long they are suspended for.

**Comment by Rythian2277** [comment]
Any suspended user on the forums at this moment is restricted to the same permissions as the public, essentially meaning that they are temporarily removed from their role on the forums. This temporary removal of the permissions should be mirrored to anywhere which is providing a forums "member only" section/service.
