### ISSUE TITLE
@everyone works with the whois command.

### ISSUE THREAD

**Issue by SUPERCHIEFYT** [evaera/RoVer#203]
If you have your nickname as `@@everyone` it will mention @everyone so 
Change this line https://github.com/evaera/RoVer/blob/3594e01a7540e8571660e15c4bd62841828d7896/src/commands/rover/WhoisCommand.js#L37 to 
```js
 let editMessage = await msg.reply(`:mag: Looking up ${member.displayName}`, {disableEveryone: true})```

**Comment by evaera** [comment]
Duplicate of #202
