### ISSUE TITLE
Unverifying Roblox Account

### ISSUE THREAD

**Issue by User3825** [evaera/RoVer#215]
I want to completely unverify any roblox account from my discord account. I used the verifying an alt but that doesnt remove the “aka” part. Is there a way to remove it? Please help

**Comment by evaera** [comment]
The "AKA" part is from Discord Nicknames and there's nothing that I can do to remove that unfortunately. You'll need to leave those servers and re-join to have your nickname removed.

**Comment by User3825** [comment]
Thanks for the help!

**Comment by VirtualizationDev** [comment]
How did you unverify your roblox account?

**Comment by DiscordCatto** [comment]
@VirtualizationDev Unlinking isn't supported currently, you would have to reverify under a different account. (also next time it would better to ask in the Discord server not in the github repo)
