### ISSUE TITLE
Unable to unbind deleted roles.

### ISSUE THREAD

**Issue by Q1exy** [evaera/RoVer#219]
I am unable to unbind these roles that were deleted on accident. I cant set another verified or unverified role until this is fixed, When I use the !unbind all command it says they were unbound but they're still there.
![Screenshot (84)](https://user-images.githubusercontent.com/55861632/65733772-af75e980-e095-11e9-95b4-99050875a8cb.png)

**Comment by evaera** [comment]
To clear those roles, run !verifiedrole and !unverifiedrole with no
arguments.

**Comment by Q1exy** [comment]
Yes, and then this happens
![Screenshot (85)](https://user-images.githubusercontent.com/55861632/65737161-3e3d3300-e0a3-11e9-87c8-b35deac99e79.png)
![Screenshot (86)](https://user-images.githubusercontent.com/55861632/65737162-3f6e6000-e0a3-11e9-944f-6df519fd662a.png)

**Comment by PhoenixShay** [comment]
Should be fixed in #225 - please try again and let us know the results @Q1exy
