### ISSUE TITLE
Support binds to Roblox Premium

### ISSUE THREAD

**Issue by HypheX** [evaera/RoVer#222]
In [the documentation](https://rover.link/#virtual-groups), there is outdated information regarding Builder's Club.

![image](https://user-images.githubusercontent.com/29693543/67822427-f8023780-fa85-11e9-83d4-9da3bd280942.png)

Builder's Club as been phased out, and replaced with Premium. The documentation, and possibly the bot API should be updated to reflect these changes in ROBLOX.

**Comment by PhoenixShay** [comment]
We are waiting on Roblox to add an official endpoint for retrieving subscription type.

**Comment by ElliottLMz** [comment]
> We are waiting on Roblox to add an official endpoint for retrieving subscription type.
This could in theory be done with [this](https://premiumfeatures.roblox.com/docs#!/PremiumFeaturesUsers/get_v1_users_userId_validate_membership) API endpoint. 

That aside, BC has *still* not been 100% phased out. With things like badges and some static pages yet to be updated!

**Comment by evaera** [comment]
To clarify, the endpoint exists, but it requires authentication. I don't want to add any binds that require authentication because it makes them fragile. So we are waiting for Roblox to provide an unauthenticated alternative.

**Comment by devSparkle** [comment]
After testing a few users, I'm pretty sure you can discern if a user is a Premium member using [this endpoint](https://groups.roblox.com/docs#!/Membership/get_v1_users_userId_group_membership_status), and checking if `membershipType > 0`.

**Comment by ElliottLMz** [comment]
The endpoint is unauthenticated, and by the looks premium is represented by `4`. I can't find any BC users so can't confirm if BC has other terms, but I'm assuming that `1`, `2`, and `3` represent BC, TBC, and OBC.

**Comment by devSparkle** [comment]
That was my understanding of it too, @ElliottLMz. Nevertheless, to account for the users that are paying for a premium-like subscription but have yet to be upgraded to one, we should have the Virtual Group return true for anything above `0`.

**Comment by PhoenixShay** [comment]
Whoops. Forgot to mention it should be fixed in 2e45881. The VirtualGroups are now Premium and NBC, and whois is now fixed as well. Docs need to be updated @evaera

**Comment by evaera** [comment]
gh-pages branch docs has docs the docs

**Comment by ElliottLMz** [comment]
Opened PR #234 to update docs.

**Comment by devSparkle** [comment]
@PhoenixShay shouldn't we rename NBC? Context will be lost over time.

**Comment by PhoenixShay** [comment]
If you have a better name than “None”, by all means open a pull request. I just don’t want it to be confusing - keep in mind it’ll be a VirtualGroup too. Binding a role to “none” would be confusing.
