### ISSUE TITLE
Error: The client user as a member of this guild is uncached

### ISSUE THREAD

**Issue by C0GYT** [evaera/RoVer#228]
Every time I try to use bindings and unbind it it keeps it forever and I can't unbind roles. Verification doesn't work for my server either and I have set it up correctly and its not working and it says working forever and nothing changes for that person. Someone please fix this.

**Comment by PhoenixShay** [comment]
src\DiscordMember.js:243:22
discord.js\src\structures\GuildMember.js:219:31 Error [GUILD_UNCACHED_ME] The client user as a member of this guild is uncached.

Awaiting advice from Discord.js team on the best way to fix - technically not our problem(?)

**Comment by C0GYT** [comment]
So i guess i'll close this issue for now
