### ISSUE TITLE
Similar discord roles will result in choosing the lesser role

### ISSUE THREAD

**Issue by slixxed** [evaera/RoVer#23]
I have 2 roles, with similar names, "Lance Corporal" and "Corporal" it will always choose Lance Corporal before Corporal

!BindGroupRank 2839176 "Corporal" 5
Added rank binding: Group: 2839176, Rank: 5, Role: Lance Corporal, Comparison: eq

**Comment by slixxed** [comment]
same goes for !BindGroupRank 2839176 Corporal 5

**Comment by devSparkle** [comment]
@slixxed are you assigning the same Rank ID to both roles?

**Comment by slixxed** [comment]
Nope, the RankID for Lance is 4, I can assign it fine but everytime I try to assign Corporal it tries to go to Lance because of the names being so similar I guess.

**Comment by evaera** [comment]
Workaround: Change the role name to something more unique, run the command, then change it back. RoVer saves role IDs, not names, so it should work.

**Comment by slixxed** [comment]
@evaera Thanks, that works, hopefully it will get patched one day as changing a bunch of role names can take a bit.

**Comment by evaera** [comment]
This is actually a bug https://github.com/Gawdl3y/discord.js-commando, not this repository.
