### ISSUE TITLE
Possible 'RobloxStaff' virtual group problem

### ISSUE THREAD

**Issue by auton0r** [evaera/RoVer#233]
In the current setup, someone is considered Roblox Staff if they are apart of the `Roblox_Staff` group on the Developer Forums. Unfortunately, this would not work in practice as `Roblox_Staff` is a *private* group.  Taking a look, only the `primary_group_name` will show `Roblox_Staff`.

An alternative way to register Roblox Staff is to use the [ROBLOX Admins](https://www.roblox.com/groups/1200769/ROBLOX-Admins) group, this group is also used in core scripts to grant the Admin badge. It should also be worth noting that a very small subset of staff are *not* in this group.

**Comment by PhoenixShay** [comment]
Anyone who isn't in this group wouldn't need to be verified as Roblox Staff anyway.

**Comment by elliottlmz** [comment]
Looks like it _is_ working currently (..somehow), however it still would not give anyone not in the `Roblox_Staff` devforum group a staff bind.

@Rythian2277 said that he is working on a new system for the RobloxStaff virtual group, which prompts staff members if they wish to be given a bound role.

**Comment by Rythian2277** [comment]
Being made by @Wolftallemo, system will read from the official Roblox group and prompt admins in DM if available whether or not they want to be shown as an admin in that guild.

**Comment by emozley** [comment]
@Rythian2277 @Wolftallemo was this ever done?
