### ISSUE TITLE
Mention everyone "bug" bypass

### ISSUE THREAD

**Issue by KingOfGenres** [evaera/RoVer#235]
One of my members discovered when using the !update command he could get it to ping everyone on accident. He went to update someone using: "!update ve" and then this is what it brought up: 

![image](https://user-images.githubusercontent.com/58674090/71755170-5c27ea00-2e81-11ea-8a64-c23108839e3f.png)

(You may say that I should not give certain people update permissions, however, it's required by some to update members roles as we're a community group which the roles are bound. So I would greatly appreciate if this was fixed, I'm hoping that there isn't a case where they end up using that to spam the discord.) 

Thank you,

King :)

**Comment by evaera** [comment]
Fixed by 5593ee65abee2dcddeecf3f85ecc959ad5796244
