### ISSUE TITLE
bot offline

### ISSUE THREAD

**Issue by costantino03** [evaera/RoVer#250]
why the bot is offline?

**Comment by mrwilyt** [comment]
According to evaera:
> Unfortunately, the reason the bot is going down is because the bot keeps getting automatically banned by Discord for a few hours at a time for exceeding their single-IP address rate limits. RoVer currently runs on one, big server instead of many, small servers. Discord's API has limits on the amount of requests that can come from a single IP address in a small time. This is my current understanding of the problem. Unfortunately Discord is not willing to work with us on solving this issue and identifying the problem points, so we are working on implementing some fixes but I don't know when or if we'll be able to fix these problems before RoVer V2 is done, which should solve this specific issue indefinitely. I'm working on RoVer V2 almost every day, but it can be hard to get a lot done after spending all day working on my full time programming job first.
