### ISSUE TITLE
RoVer fights with itself.

### ISSUE THREAD

**Issue by minaise123** [evaera/RoVer#26]
Hello! Looks like RoVer started fighting with itself. I have 3 bots on the server, and the other two cant cause this. Screenshot of the "fight" is added. Sorry for that bad quality.

How to fix it?

![rover glitch](https://cloud.githubusercontent.com/assets/28870911/26319582/471c80d0-3f28-11e7-9522-fed24f2d2d2f.jpg)

**Comment by evaera** [comment]
Do you have more than one role linked? (including the verified role)

**Comment by minaise123** [comment]
Yes, I have. I have 9 ranks linked.

Parimate soovidega,
Antonyo Villakov

2017-05-22 23:05 GMT+03:00 Eryn Lynn <notifications@github.com>:

**Comment by evaera** [comment]
Don't like more than one role to a binding, it will fight with itself like that
