### ISSUE TITLE
RoVer resets my prefix over time.

### ISSUE THREAD

**Issue by CStarGamer** [evaera/RoVer#264]
Last night, I made sure my prefix was right in my server. (I set it to `r!` in my case.)
Today, when I woke up and tried using the same prefix, it did not work. Apparently, the prefix was set back to the default `!`. No one tinkered with it at all during the night, so I found the prefix change very weird.

![image](https://user-images.githubusercontent.com/42369836/83948644-87c24e00-a7ec-11ea-9d65-da7eadd20e19.png)

**Comment by griuhse** [comment]
Same for me it seems like that happens only when the bot goes offline and back online

**Comment by DiscordCatto** [comment]
Due to the way discord.js-commando works it stores the prefix in memory once the memory gets wiped so does the prefix any server sets, most likely evaera has a fix for V2 for this issue.

**Comment by evaera** [comment]
> Due to the way discord.js-commando works it stores the prefix in memory once the memory gets wiped so does the prefix any server sets, most likely evaera has a fix for V2 for this issue.

This is not correct

**Comment by PhoenixShay** [comment]
Did any other settings get reset? Does this problem consistently happen?

**Comment by CStarGamer** [comment]
> 
> 
> Did any other settings get reset? Does this problem consistently happen?

Hmm... I haven't used RoVer in a while and I did not try out other settings. Sorry, I couldn't give you the answer for that one.

What I can say is this consistently happens. (It changes around every day, perhaps a couple of hours.)
