### ISSUE TITLE
Unbindong and verified role rank setting problems

### ISSUE THREAD

**Issue by somerandomguy100** [evaera/RoVer#267]
So I am trying to set up the ROver on my server and it's not setting the verified rank it's only removing the unverified rank which I have to put on myself and it's also not letting me unbind the rank so I cant rebind it

**Comment by Code-Sync** [comment]
> So I am trying to set up the ROver on my server and it's not setting the verified rank it's only removing the unverified rank which I have to put on myself and it's also not letting me unbind the rank so I cant rebind it

To unbind the verified/unverified roles you run !verifedrole or !unverifiedrole respectively. To bind to it, you would run !verifiedrole <role> or !unverifiedrole <role>. If you need help join the discord server; link found on https://rover.link/
