### ISSUE TITLE
The ability to unlink or change your account

### ISSUE THREAD

**Issue by slixxed** [evaera/RoVer#27]
From what i understand at the moment once your account is linked that is pretty much it, like if you accidentally link an alt or change accounts, it would be helpful to unlink your discord/ROBLOX so you do not have to make a new discord.

**Comment by evaera** [comment]
You can just re-link with another account. There's nothing stopping you from doing so.

**Comment by slixxed** [comment]
Oh, someone was having an issue with this and I thought it wasn't a thing, sorry for wasting your time.
