### ISSUE TITLE
How to "unverify" for testing?

### ISSUE THREAD

**Issue by OurPub** [evaera/RoVer#271]
This is probably just me not understanding, but is there a way to "unverify" a user, basically to unlink a Discord user from their Roblox account? I ask because it seems difficult to test the flow of a new user coming to a Discord server, verifying, and on my side making sure this works properly. This is because after you do a verify it's forever (?) linked. One solution is to continuously create Discord accounts, but this is tedious because now they verify with a text message to a cell phone, etc?

**Comment by PhoenixShay** [comment]
Unverification is not supported by verify.eryn.io, which is a separate project. The bot verifies you as if you typed !verify when you join the server - why do you need to type !verify to ensure it’s working?

**Comment by OurPub** [comment]
So first off I want to test with a Discord user as if they have not been verified (aka linked). Is there a way to do this? One way I thought of is to simply unlink the Discord account from the Roblox account.

**Comment by Code-Sync** [comment]
Verification should not be used as a key to unlock access to your server. It’s sole purpose is to determine who has verified with RoVer, and who hasn’t.

**Comment by evaera** [comment]
> Verification should not be used as a key to unlock access to your server.

why not?

**Comment by OurPub** [comment]
I guess maybe I'm asking the question incorrectly. When I setup my Discord server (which I'm new to) I'm setting up various categories, channels, roles, etc. When someone joins my server they see one thing (based on their verification or not). However, after they verify themselves they will then see different categories/channels based on my setup as they get granted the "verified" role. I just want to test this flow.

**Comment by evaera** [comment]
you should make an alternate discord account!

**Comment by OurPub** [comment]
I did, then I linked it (which I wish I hadn't), and now when I try to create another Discord account it wants to use my cell # during account setup. However, Discord being clever, detects I've used this cell already :)

**Comment by evaera** [comment]
Can't you just remove the verifeid role from your alternate account manually from your main account?

**Comment by Code-Sync** [comment]
> why not?

Most people who ask about this have the wrong idea about verification; where it is necessary to run the !verify command in order to unlock the server and give access to those who run the command, instead of automatically giving out the respected verification role, and any other bindings. You can use channel permissions to prevent roles from seeing/typing in channels, sure, but from my understanding, what I described above isn’t the intended purpose of verification.

**Comment by OurPub** [comment]
> Can't you just remove the verified role from your alternate account manually from your main account?

That's a tongue twister: Are you saying that one way to simulate this is by removing the "Verified" role from my main account?

**Comment by evaera** [comment]
yes

**Comment by OurPub** [comment]
Thanks for that. It still leaves the developer no easy way to test the "Unverified" role in this situation, but it's a good idea.

Now my last question is still related to unlinking an account. When I created my alternate Discord account I unwisely tied it to my same Roblox account as with my main Discord account. Is there a way to unlink?

**Comment by evaera** [comment]
You can just give your alt the unverified role ...

And no as mentioned above, there isn't a way to unlink

**Comment by OurPub** [comment]
Well, there is one way and that's to delete the Discord account and then recreate it, but apparently it takes 14 days for them to permanently delete. They are too clever for their own good!

Thx to both of you for the help.
