### ISSUE TITLE
Unresponsive

### ISSUE THREAD

**Issue by crazymanclan** [evaera/RoVer#28]
So when I used the and I put all the links to the roles right. A few hours or so I try to use !update or bind another role and the bot just won't respond back i don't know what it could be. 
![image](https://cloud.githubusercontent.com/assets/28937103/26427483/e9eaa264-40aa-11e7-8b54-cdc4070a17a0.png)

**Comment by devSparkle** [comment]
Does the bot have access to the channel / administrator permissions? @crazymanclan

**Comment by crazymanclan** [comment]
It has all the permissions. It's like it works for a moment enough to do my stuff but after that it just completely useless.

**Comment by crazymanclan** [comment]
@

**Comment by crazymanclan** [comment]
Then there's delayed responses which is annoying

**Comment by evaera** [comment]
Updated packages, seeing if it will fix, open if experience again
