### ISSUE TITLE
Allow server owners to reverify users

### ISSUE THREAD

**Issue by jaherron** [evaera/RoVer#281]
There should be an option for a server owner to manually reverify any user as long as they've already confirmed their ROBLOX account with the verification server.

The suggestion for command format:
!verify @Username#2389

**Comment by suufi** [comment]
Are you referring to the !update command? This already exists.

**Comment by mrwilyt** [comment]
When a user reverifies, the account they previously verified with is overwritten with the new account. Any old data prior to reverification is gone.
