### ISSUE TITLE
A setting so the bot wont verify people when they join 

### ISSUE THREAD

**Issue by iiLikeNuts** [evaera/RoVer#282]

**Comment by evaera** [comment]
Please provide a use case

**Comment by iiLikeNuts** [comment]
> Please provide a use case

It would be useful for servers that want a 2 step verification kind of thing,
react that you agreed to the rules and it shows a channel to verify your roblox account, after that you can get access to all the channels

**Comment by evaera** [comment]
Couldn't you do that anyway, just in reverse?

**Comment by mrwilyt** [comment]
This was kind of mentioned in #249.
