### ISSUE TITLE
Can't start the bot and can't run !getroles or !update

### ISSUE THREAD

**Issue by VinDotRun** [evaera/RoVer#284]
Hello,

The bot is returning this error after starting:
```js
Launching shard 1/1
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'array' of undefined
      at DiscordBot.ready (C:\...\src\DiscordBot.js:241:91)
      at CommandoClient.emit (events.js:194:15)
```

Using a old version of DiscordBot.js I started the bot normally, and this error happened when trying to do !getroles or !update:
```js
(node:9760) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'find' of undefined
    at DiscordMember.verify (C:\...\src\DiscordMember.js:239:33)
```
On the server, the bot keeps saying "Checking permissions..."

**Comment by evaera** [comment]
> Self-hosting is recommended for advanced users only who are experienced with the Node.js ecosystem. Note that setup or code support will not be given for attempting to run your own instance of RoVer, modified or otherwise.
