### ISSUE TITLE
When i do npm install it give me an error

### ISSUE THREAD

**Issue by soudblox** [evaera/RoVer#285]
I have node installed and it's the highest version.
and when i try to do npm install it give me this error:
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/discordapp/erlpack.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Roaming\npm-cache\_logs\2020-10-30T06_56_00_490Z-debug.log

**Comment by ElliottLMz** [comment]
We do not provide support for self-hosting.

**Comment by soudblox** [comment]
oh sorry
