### ISSUE TITLE
RoVer won’t let me bind discord roles that have spaces

### ISSUE THREAD

**Issue by KittenTech** [evaera/RoVer#286]
I’ve read through the entire Rover website (Rover.link) and cannot get RoVer to bind discord roles with spaces in them to my Roblox group ranks. I have tried it with and without quotation marks around the discord role. It just says that it’s an invalid role every time. I’ve checked multiple times to be sure I didn’t misspell it or something like that. Binding single word ranks works just fine, it’s only the ones with spaces that won’t work.

**Comment by Code-Sync** [comment]
Are you, by chance, trying to bind on mobile? If so, mobile quotes don't work. You have to use computer quotes ( "" ).

**Comment by KittenTech** [comment]
Oh, ok, I hadn’t thought about that being an issue. I didn’t have access to a computer at the time, so I did it on mobile. Thank you.
