### ISSUE TITLE
Rover Help

### ISSUE THREAD

**Issue by YourAveragePlayer** [evaera/RoVer#287]
Umm How do I change the prefix because I have MEE6 And Rover nd they have the same MEE6 Devs said it was coming in the near futher changing the prefix so I figured why not ask Rover devs or any of their community.

**Comment by evaera** [comment]
![image](https://user-images.githubusercontent.com/2489210/99010109-537b5800-2517-11eb-8b4c-66efd8f3b121.png)

**Comment by YourAveragePlayer** [comment]
Thanks again.
