### ISSUE TITLE
Rank Doesn't Work?

### ISSUE THREAD

**Issue by gtc122004** [evaera/RoVer#29]
So I tried to bind me (the owner) to the top rank in my group (255) This is the result I got:

ME: !bindgrouprank 2724037 B0SS NOOB 255

RoVer: @gtc122004, Added rank binding: Group: 2724037, Rank: none, Role: B0SS NOOB, Comparison: eq

As you can see it does not say Rank: 255

ummmmm. yeah

**Comment by crazymanclan** [comment]
Yea it happens to me too it seems if the rank has a spac it won't register but you can try B0SS/NOOB

**Comment by devSparkle** [comment]
@gtc122004 please follow these instructions:

1. Removed the space from the rank
2. Bind the rank using `!bindgrouprank 2724037 B0SSNOOB 255`
3. Re-add the space to the rank

RoVer will automatically deal with any name changes to the rank and it should now be linked!
