### ISSUE TITLE
Respecting Community Server Rules Screening feature

### ISSUE THREAD

**Issue by Rythian2277** [evaera/RoVer#293]
As of 21/12/2020 (DD/MM/YYYY) Discord introduced the new Rules Screening feature which essentially makes it so users must agree to rules before they're allowed to access the server, helping **Community** servers with people not reading the rules.

With Discord's announcement message, they state that any bots which award a role on joining will automatically bypass this feature, making it unusable with the current state of Rover.
> P.S. If you grant roles to new members on join via a bot, it will bypass this feature. We recommend updating your bot to only grant roles once members pass the screening. Look for the pending flag in our developer documentation.

This isn't currently possible with Discord.js v12 and won't be available until v13 so any temporary patch measure until v13 is released (soon™) for those who use Rover in their Community Servers.

**Comment by Rythian2277** [comment]
A temporary fix for those wanting this functionality is to disable JoinDMs **(!joindm false)** until it can be automated based on the API

**Comment by elliottlmz** [comment]
similar #249 

does the new rules screening api include an api for determining if someone has passed other screenings (e.g. verified email) and is now safe to role? or does the new api _just_ say if user has passed rules screening.

**Comment by DaStormer** [comment]
> does the new rules screening api include an api for determining if someone has passed other screenings (e.g. verified email) and is now safe to role? or does the new api _just_ say if user has passed rules screening.

Well, in this context, there isn't really any **direct** way to determine whether a GuildMember has verified email, per se. There _is_ a verified boolean property in the User object, but that requires the email OAuth2 scope.

However, a **verified email is part of the member rules screening**. Discord does not let you submit the agreement to rules if you do not have a verified email. So technically, the pending property in the GuildMember object should be completely "accurate" in determining whether a member has passed Discord verification steps.

**Comment by Rythian2277** [comment]
Just a note regarding this, this isn't going to be possible for quite a while either way as it's not available in discord.js

Once it's available either me or @Wolftallemo will PR in a patch and hopefully get it implemented ASAP

**Comment by AnaheimDucks16** [comment]
Can you make it so you can set a delay in giving the role with RoVer?

**Comment by Rythian2277** [comment]
Why would a delay feature be needed?

**Comment by AnaheimDucks16** [comment]
Say, they already verified with RoVer. And they join a new server with RoVer and the server has a rules screening feature where you have to be a member for 10 mins. This is bad since they would automatically get the role gaining access to the server.

**Comment by DaStormer** [comment]
v13 got released today! 🙂

Implementing this will require updating the code a lot though to support breaking changes

Commando isn't supported anymore 😬

**Comment by emozley** [comment]
Is there anything new on this?

**Comment by Wolftallemo** [comment]
As of now no, we can't until we update to djs 13 which would break commando.
