### ISSUE TITLE
!whois issue. (Bio failed to load)

### ISSUE THREAD

**Issue by realgavinmartin** [evaera/RoVer#297]
When you run !whois on someone if sends back "Bio failed to load".

![botissue](https://user-images.githubusercontent.com/47824008/104042440-843edd00-51a8-11eb-9256-ca6c0f55f594.PNG)

**Comment by iialexidai** [comment]
Yes Eryn already knows about the issue. She decided to load the bio information by downloading a user's entire profile page and Roblox isn't too happy. @Wolftallemo is currently working on a fix for it which should hopefully be released soon!
