### ISSUE TITLE
Adding Automatic help and diagnostics

### ISSUE THREAD

**Issue by Rythian2277** [evaera/RoVer#298]
I suggest that we add automatic checking when a role is bound if the role is above RoVer and if it is, warning the owner.

Alongside this I'd also suggest adding more error messages which are more specific on how to fix the issues such as a modification to how RoVer plus warns users about not being a patron and to try the steps we would normally suggest to users.

This could be extended in turn to all elements of rover which we're constantly having to explain how to fix in the server.

**Comment by PhoenixShay** [comment]
Make a pull request bro

**Comment by Rythian2277** [comment]
This was an issue for me to fix when I get home from work 🙃
