### ISSUE TITLE
Roblox User Membership info api

### ISSUE THREAD

**Issue by Wizkiller96** [evaera/RoVer#302]
Not sure if Roblox put this under a new API or just removed it entirely but from check https://groups.roblox.com/v1/users/{userid}/group-membership-status it no longer provides the information about a users membership status. Not sure if you already knew but just wanted to let you know if you haven't notice yet.

**Comment by Wizkiller96** [comment]
Seems this is the new way to check user premium status https://premiumfeatures.roblox.com/v1/users/{userid}/validate-membership

**Comment by Rythian2277** [comment]
We're looking into fixing this but Roblox has decided their new API endpoint for membership checking `https://premiumfeatures.roblox.com/v1/users/<Buserid>/validate-membership` requires a cookie from a logged in account to access.

**Comment by Wizkiller96** [comment]
I just notice that is kind of annoying that they did that for something most people could see publicly anyway.

**Comment by Wolftallemo** [comment]
Alright well this has been fixed (as have what we believe are the rest of the old endpoints)
