### ISSUE TITLE
Bot not starting

### ISSUE THREAD

**Issue by noah01q** [evaera/RoVer#312]
![image](https://user-images.githubusercontent.com/72419462/107108572-d8f86680-67ed-11eb-9e28-4cd5b1a1b8a0.png)

**Comment by noah01q** [comment]
Someone help please.

**Comment by PhoenixShay** [comment]
We do not provide support for self hosted bots

**Comment by noah01q** [comment]
Oh ok.

**Comment by TheCoolOne123** [comment]
Run ``npm i``, not ``npm i -g``

**Comment by iialexidai** [comment]
> We do not provide support for self hosted bots

@TheCoolOne123 🥴
