### ISSUE TITLE
Add 'unverify' as an alias of 'support'

### ISSUE THREAD

**Issue by Rythian2277** [evaera/RoVer#327]
Since users can only be unverified by official RoVer support staff, it may be better to redirect those who wish to unverify to the support server to make their request instead of having no available information on how to unverify.

An update to the pages may also be needed to include this information.

**Comment by Wolftallemo** [comment]
I would ultimately prefer a separate command so that we can make the dm more clear instead of the generic support message, but neither solution is particularly hard.

**Comment by Rythian2277** [comment]
Perhaps have it respond with a "go to DMs" and explain in DMs about what to do in detail?

**Comment by Wolftallemo** [comment]
That's more or less what I was going after, but I should have time tonight.
