### ISSUE TITLE
I can't start the bot...

### ISSUE THREAD

**Issue by M-a-s-o-n-C** [evaera/RoVer#329]
### Troubles
Hiya. So, when I try and start the bot, after I have added my token, ofc. I keep getting this error:

### Error Message:
`internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/home/runner/RepentantJumpyBrains/src/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}`

### ------
I don't know if it is something I am doing wrong, but it is not working. I am new to this stuff, so it could be a noob mistake. Someone please help! 

(Also, the command I run in the **Shell** is **node ./src/index.js**.

**Comment by PhoenixShay** [comment]
We do not support self hosting. Please make sure you are in the correct directory and are following the guide.

**Comment by suufi** [comment]
You also shouldn't be running bots on repl.it.
