### ISSUE TITLE
DiscordMember double fetch?

### ISSUE THREAD

**Issue by GoldenAngel2** [evaera/RoVer#341]
It looks like the bot double fetches the member information. 
https://github.com/evaera/RoVer/blob/master/src/DiscordMember.js#L164
and 
https://github.com/evaera/RoVer/blob/master/src/DiscordMember.js#L170
> This just seems out of place and an oversight. 

Also shouldn't you just use the `force` option for that, so it always fetches the new data?

**Comment by Rythian2277** [comment]
This is an intended block of code. We may review it's functionality soon but at this time, it works as expected and we have not encountered any issues with this method.
