### ISSUE TITLE
Former Usernames Appearing

### ISSUE THREAD

**Issue by GeorgeTheDevRBX** [evaera/RoVer#342]
As a note, I use RoVer Plus, not the free RoVer.

As of lately, I've noticed users having their older usernames get put as their nickname rather than their current username. 
![image](https://user-images.githubusercontent.com/86137441/122628651-20c8ad80-d06c-11eb-9549-7ee425ffebcd.png)

In this particular case, the username the bot gave the user was his first account username, rather than his current username.

**Comment by Wolftallemo** [comment]
Roblox has been giving us trouble for some time now. In cases where we are unable to retrieve their latest username we fall back to the name stored in the verification registry, hence why some users are getting old usernames.

I've been looking at request proxying to fix this and I can't come up with a good time estimate for it. In the meantime they can go back to the [verification page](https://verify.eryn.io) if they want to update the name stored.

**Comment by evaera** [comment]
I don't think we should do any request proxying. Our server automatically splits requests over a few different IP addresses. We should see if we can have better fallback behavior or save more recent usernames.

**Comment by Wolftallemo** [comment]
I think we could add this to the registry, probably by sending a patch request to `/api/user/:id` with the new username, and add this to the bot to do this should the username we have doesn't match what roblox provides (if an api key is set)
