### ISSUE TITLE
The bot keeps blacklisting the server

### ISSUE THREAD

**Issue by daulric** [evaera/RoVer#365]
I recently added RoVer to my server and it kept saying that this server has been blacklisted

**Comment by Code-Sync** [comment]
Hello. If your server is blacklisted then you, or the owner of the server if that is not you, is banned from the support server for RoVer.

The link to appeal from termination can be accessed here: https://dyno.gg/form/3c3f8583

**Comment by Rythian2277** [comment]
Your appeal has been reviewed and you have been unbanned. This now means that your server is no longer Blacklisted.
