### ISSUE TITLE
RoVer verification thread unresponsive after prolonged run time.

### ISSUE THREAD

**Issue by devSparkle** [evaera/RoVer#38]
The thread responsible for handling verification ceases to process and respond to `!Verify` and `!Update` commands after a prolonged run time.

This issue is currently under investigation and I have posted this to prevent duplicate posts such as #33, #32, #30 and others.

**Comment by slixxed** [comment]
Can confirm; happens very often.

**Comment by devSparkle** [comment]
@slixxed this issue was massively improved upon and is still being worked on.

**Comment by slixxed** [comment]
@devSparkle Seems to be getting worse in my discord server? Not that I doubt it's being worked on^

**Comment by evaera** [comment]
I hope I finally fixed this once and for all!
