### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by ConnorThomp** [evaera/RoVer#42]
I keep getting this message and I don't know how to fix it: RoVer couldn't modify the member in this server. Either the bot doesn't have permission or the target user cannot be modified by the bot (such as higher rank in the server).

**Comment by PhoenixShay** [comment]
If you'd like, post an invite link and I can fix it up for you. Otherwise:
1. Is RoVer below the rank of the person being verified?
2. Does RoVer have the manage role permission?

**Comment by ConnorThomp** [comment]
https://discord.gg/ecPk6AT

**Comment by ConnorThomp** [comment]
I also added a new ROBLOX BOT that has advanced features. One is also verify, but I find the process too tedious. RoVer is much quicker.
