### ISSUE TITLE
Bot does not auto-DM new users when they join a server

### ISSUE THREAD

**Issue by LouieK22** [evaera/RoVer#43]
The bot is most likely being rate-limited since so many new users are joining.

This hosted bot experiences this issue, but when running it myself to test the issue did not appear. Leading me to believe it's a rate-limiting issue.

**Comment by PhoenixShay** [comment]
Hey there. Glad you could report this issue - please reply with an invite link to your Discord so we can investigate.

**Comment by LouieK22** [comment]
discord.me/jkr

**Comment by evaera** [comment]
Appears to not occur anymore.
