### ISSUE TITLE
Bot will not auto-DM new users on servers with high verification levels

### ISSUE THREAD

**Issue by devSparkle** [evaera/RoVer#44]
The RoVer bot will not automatically DM users information in cases where the server has subjected users to higher verification levels, such as "Must be a member of this server for longer than 10 minutes" and "Must have a verified phone on their Discord account".

The trend displayed in #43 is common on servers where the user does not instantly get the ability to interact with the server and may possible be related with a `Discord.js` API issue.

**Update:** Upon further investigation, the event responsible for handling new players in the server will not fire in these specific server types.

This also causes an issue with players who are already registered within the RoVer database, which will not be automatically verified as expected.

**Comment by devSparkle** [comment]
Upon further investigation, the event responsible for handling new players in the server will not fire in these specific server types.

This also causes an issue with players who are already registered within the RoVer database, which will not be automatically verified as expected.

**Comment by devSparkle** [comment]
@evaera where is the duplicate issue?

**Comment by evaera** [comment]
#43
