### ISSUE TITLE
Question on Verification

### ISSUE THREAD

**Issue by stopthebadpuns** [evaera/RoVer#46]
Is there a way for a user to "unverify" themselves? Just out of curiosity.

**Comment by devSparkle** [comment]
@stopthebadpuns there is no command for a user to unverify themselves.

**Comment by stopthebadpuns** [comment]
Oh ok, thanks for letting me know at least...but that still sucks. ;-;

**Comment by devSparkle** [comment]
@stopthebadpuns why so? What is the use case for this feature?

**Comment by PhoenixShay** [comment]
Yeah, not sure what you'd need to unverify yourself for.

**Comment by evaera** [comment]
regardless, not relevant to this project
