### ISSUE TITLE
Name Changes

### ISSUE THREAD

**Issue by stopthebadpuns** [evaera/RoVer#47]
Hi, I just wanted to know if changing your username on Roblox...changes the nickname on Discord? Thanks in advance.

**Comment by evaera** [comment]
No, you need to verify again on verify.eryn.io

**Comment by devSparkle** [comment]
@stopthebadpuns to have your username updated, you should:

1. Head to [verify.eryn.io](verify.eryn.io) and follow the verification process
2. Say `!verify` on one channel within your server where RoVer is present
3. Repeat **step 2** for other servers
