### ISSUE TITLE
Feature Request: Don't act on users with a role named "RoVer Bypass"

### ISSUE THREAD

**Issue by SignallerRBLX** [evaera/RoVer#62]
Instead of removing roles given to them by an admin, is it possible to stop the bot from removing it because they aren't in the rank?

**Comment by evaera** [comment]
@SignallerRBLX I believe you can achieve this by creating a "RoVer Bypass" role that's just above the "RoVer" role hierarchically, then RoVer shouldn't be able to change their roles. If this isn't the current behavior (it may only work with nicknames...) then I'll add it in manually

**Comment by SignallerRBLX** [comment]
@evaera Problem is that role is being used for a rank so people can automatically get it. The person who I assign the role manually does not have enough group space to join the side group so it will keep taking it away.

**Comment by suufi** [comment]
@SignallerRBLX :eyes: That's why she said create a role called `RoVer Bypass` that's above `RoVer`. When you give the person the role you want to manually give, also give them `RoVer Bypass`.

**Comment by SignallerRBLX** [comment]
@suufi Does not work, that's why I explained it.

**Comment by suufi** [comment]
Try making the role itself you're giving higher than `RoVer`.

**Comment by SignallerRBLX** [comment]
@suufi Then the bot cannot give the role out to others.

**Comment by evaera** [comment]
If I add a special case for users with a roll called "RoVer Bypass" to be ignored, it will ignore them entirely, meaning they won't get verified. Maybe it would make more sense to only make it bypass group bindings. That distinction doesn't seem intuitive for server owners though.
