### ISSUE TITLE
Only allows me to put in one server

### ISSUE THREAD

**Issue by jbh2007** [evaera/RoVer#64]
it only allows me to put it in one server, and i dont even need that server (oh and im jbh2007)
![image](https://user-images.githubusercontent.com/33398388/33299082-8f3c4d2a-d3af-11e7-9933-6ca71b3b5412.png)

**Comment by jbh2007** [comment]
#

**Comment by evaera** [comment]
You can only add RoVer to servers that you have the Manage Server permission on. It says it right there in your screenshot. Further, if there was any problem with that page, that is on Discord's website and not anything to do with RoVer.

**Comment by jbh2007** [comment]
but thats not the server i need, i need another server.

**Comment by jbh2007** [comment]
and im the owner to that server.

**Comment by jbh2007** [comment]
im starting to think that it is a problem with Discord.

**Comment by evaera** [comment]
I think you are probably logged in to the wrong account in your browser. Go to discordapp.com and log out.

**Comment by jbh2007** [comment]
oh wait i am

**Comment by jbh2007** [comment]
im such a idiot, and thanks for telling me
