### ISSUE TITLE
!Nick command for users

### ISSUE THREAD

**Issue by MitchelValentine** [evaera/RoVer#92]
Problem is in the title.
Basically, I can't have a bot change a user's nickname to the template, and then let them change the first part without it changing it back. I understand that this is an intended feature, but could you add in another feature that would allow users to modify part of it, or even keep the nickname to a template like

> %NICKNAME% - (%ROBLOXNAME%)

**Comment by evaera** [comment]
@MitchelValentine Do you think that base discord account name isn't enough for users? This would be a lot of work for such a small feature.

**Comment by MitchelValentine** [comment]
I believe that everyone could live without this, and that a select few
would like this feature.... Tbh if it's THAT much effort I'd go your way
and not implement it.

**Comment by evaera** [comment]
This would require adding a !nick command. Storing user nicknames in the server settings might be a bad idea. Will think about this some more..

**Comment by evaera** [comment]
Requires #97 first
