### ISSUE TITLE
Need a more feasible data storage solution

### ISSUE THREAD

**Issue by evaera** [evaera/RoVer#97]
Or do we

**Comment by PhoenixShay** [comment]
I've tried http://lokijs.org/ before and I think it would work well for this purpose

**Comment by iranathan** [comment]
use mongodb

**Comment by buoyantair** [comment]
Better yet, use mongodb /w mongoose :)

**Comment by JMGbaum** [comment]
You can also use sqlite to store objects and/or strings that you can later evaluate.

**Comment by accidentalmeme** [comment]
CouchDB is a database server that natively uses http.

**Comment by FreeLineTM** [comment]
I am not completely aware of how data is currently stored in RoVer, but if there is structure to it, and the data is predictable, then Postgres or MySQL is probably a safe choice.
